'use client';
import {useState} from 'react';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const faqs=[
['“My spouse already knows.”','Ask them which account pays the insurance and where the current policy is. Any answer that starts with “I’d ask you” is a detail worth leaving in the binder.'],
['“I already have notes and a will.”','Keep them. The binder connects the practical details: what exists, where it is, and who to contact. Your will handles a different job.'],
['“Our household is complicated.”','That’s more for someone else to piece together. Work through the guided sections one at a time, starting with the accounts and responsibilities that matter most.'],
['“What about security?”','You choose where to store your completed binder and who can access it. You can reference a password manager or secure document location rather than include passwords. Protect digital copies and keep printed copies somewhere secure.'],
['“What exactly do I receive?”','A digital PDF and Notion template, all eight information sections, a printable safe-copy, and lifetime updates. Fill it in digitally, print it, or use both.']
];
export default function Home(){const[bump,setBump]=useState(false);const[open,setOpen]=useState(false);return <main className="focused-sales"><div className="hero-shell"><nav className="nav wrap"><a className="brand" href="#">THE FAMILY SAFEKEEP<span>IN CASE OF EVERYTHING.</span></a><a className="nav-cta" href="#offer">Get the binder — $27 ↗</a></nav><section className="hero wrap direct-hero"><div><p className="eyebrow">FOR THE PEOPLE WHO COUNT ON YOU</p><h1>If you were in hospital tonight,<br/><em>who would know how<br/>everything works?</em></h1><p className="lead">Give your family the answers before they have to ask. The “If I’m Not Here” Binder puts your accounts, insurance, bills and essential instructions in one place — so they have somewhere to turn when they can’t turn to you.</p><a className="button" href="#offer">Get My Family Binder — $27 <span>→</span></a><p className="micro">PDF + Notion · Instant download · One-time payment</p></div><div className="hero-aside"><img src="https://storage.googleapis.com/msgsndr/fveUHPreYRqiA1APSbJt/media/694ed94d73a5e00f27327df7.jpg" alt="A woman at her kitchen table facing household paperwork"/><div className="photo-caption hero-realisation">You’ve taken care of so much.<br/>Let this be one less thing they have to figure out.</div></div></section></div>
<section className="section wrap" id="recognition"><p className="eyebrow">THE INVISIBLE JOB YOU DO</p><h2>You’re not just part of the household.<br/>You’re its <em>search engine.</em></h2><p className="intro">“Where’s the policy?” “Which account pays that?” “What’s the login?”<br/>They ask. You answer. Life moves on.</p><div className="recognition-grid">{['You know which account pays the mortgage.','You know where the insurance documents are.','You know which login connects to which email.','You know who to call when something goes wrong.'].map((x,i)=><div key={x}><span>0{i+1}</span><p>{x}</p></div>)}</div><p className="punch">It feels like being organised.<br/><strong>Until you realise the system is you.</strong></p></section>
<section className="dark"><div className="section wrap split"><div><p className="eyebrow">WHEN “JUST ASK ME” ISN’T AN OPTION</p><h2>They’re already worried about you.<br/><em>Now they’re searching drawers.</em></h2></div><div><p>Your phone is locked. The insurer wants a policy number. A bill has arrived, and your partner doesn’t know whether it’s already being paid.</p><p>They remember a folder. Or was it an email?</p><p className="standout">You had it all somewhere.<br/>But “somewhere” is a hard place to look when they can’t ask you.</p><p>A hospital stay. An accident. A few days out of contact. Ordinary life keeps asking questions.</p></div></div></section>
<section className="wrap short-bridge"><h2>The missing piece is<br/><em>the part only you know.</em></h2><p>Your notes hold fragments. Your folders hold documents. Your will serves its own purpose. But none of them automatically explains how the pieces fit together.</p><p><strong>That’s what you’re leaving your family: the answers, organised so they can find them.</strong></p></section>
<section className="section wrap tangible-product" id="inside"><div className="tangible-copy"><p className="eyebrow">FROM “I REALLY SHOULD” TO “IT’S ALL HERE”</p><h2>The Family Safekeep</h2><p className="product-subtitle">The “If I’m Not Here” Binder</p><p className="product-explanation">You don’t have to invent the system or remember what to include. Eight guided sections turn the details in your head into a reference your family can use.</p><div className="contents-list">{[['Master Account Registry','Bank accounts, investments and credit cards. Let them know what exists and where to look.'],['Insurance Command Center','Insurers, policy details and contacts. Give them a starting point for the call.'],['Digital Life Decoder','Phones, email and digital accounts. Point them to the access arrangements you’ve made.'],['Autopay Map & Bill Calendar','What gets paid, when, and from which account. Make the routine visible.']].map(([h,p])=><div key={h}><span aria-hidden="true">✓</span><div><h3>{h}</h3><p>{p}</p></div></div>)}</div><div className="four-more"><strong>Plus the details you don’t want to leave out</strong><p>Medical Quick-Reference · Emergency Contacts · Physical Asset Guide · Digital Wealth</p></div></div><div className="tangible-visual"><div className="safekeep-preview"><p className="eyebrow">THE FAMILY SAFEKEEP</p><h3>“It’s all here.”</h3><p>The accounts. The people to call.<br/>The details they’d otherwise ask you.</p><div className="safekeep-preview-contents"><strong>A look inside: the questions that matter</strong><p>Which account is this?</p><p>What is it used for?</p><p>Where can the details be found?</p><p>Who should they contact?</p></div><small>ILLUSTRATIVE SECTION PREVIEW · PDF + NOTION</small></div><div className="product-delivery"><strong>Follow the prompts. Fill in your details.<br/>Show your family where it is.</strong><p>PDF + Notion template · Printable safe-copy<br/>Lifetime updates included</p></div><a className="button" href="#offer">Get My Family Binder — $27 <span>→</span></a></div></section>
<section className="original-proof"><div className="wrap"><div className="proof-stars" aria-label="5 out of 5 stars">★★★★★</div><blockquote>“I've been saying I need to do this for literally 5 years. Finally sat down with this and knocked it out in one evening with a glass of wine. My husband was like 'wait, we have a life insurance policy?' YES BRIAN, WE DO. 😂 Worth every penny just for that conversation.”</blockquote><p><strong>Michelle K.</strong> · New York, NY</p><small>Customer testimonial from The ICE Vault</small></div></section>
<section className="section wrap compact-confidence"><div><p className="eyebrow">THE RELIEF IS HAVING IT DONE</p><h2>Imagine showing them<br/><em>where everything is.</em></h2><p>No trying to remember which drawer. No “I’ll write it down later.” A binder you can open together and say: <strong>“If you need this, start here.”</strong></p><p>The prompts give you a place to begin and a path through the details. Work section by section. Check anything missing. Then put the completed copy somewhere your trusted person can find it.</p><p><strong>You’ve carried this in your head long enough.</strong></p></div><div className="faq">{faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
<section className="offer-backdrop"><div className="section wrap offer-section" id="offer"><div><p className="eyebrow">ONE LESS THING TO KEEP MEANING TO DO</p><h2>Give them the answers.<br/><em>Give yourself the relief.</em></h2><p className="intro">For $27, get the structure to turn years of “I should organise this” into something your family can actually use.</p><blockquote className="offer-testimonial">“Filled this out, printed a copy for the safe, and shared the digital version with my sister. For the first time in my adult life I feel like I have my sh*t together. My husband cried when I showed him.”</blockquote><p className="testimonial-credit">— Amanda T.<br/><small>Customer testimonial from The ICE Vault</small></p></div><div className="offer-card"><p className="eyebrow">THE “IF I’M NOT HERE” BINDER</p><div className="price"><del>$67</del><strong>$27</strong><span>LAUNCH PRICE<br/>ONE-TIME PAYMENT</span></div><ul>{['All 8 guided information sections','PDF + Notion template','Printable safe-copy','Lifetime updates'].map(x=><li key={x}>✓ <span>{x}</span></li>)}</ul><label className="bump"><Checkbox checked={bump} onCheckedChange={setBump}/><span><strong>Add the “First 48 Hours” Crisis Checklist</strong><br/>Give them a sequence to follow through the immediate crisis.<br/><b>+ $17</b> <small>Optional</small></span></label><button className="button buy" onClick={()=>setOpen(true)}>Get My Family Binder <span>→</span></button><p className="order-total">Your total: <strong>${bump?44:27}</strong> · One-time payment</p><p className="micro">Instant digital download · PDF + Notion</p></div></div></section>
<section className="guarantee"><div className="wrap guarantee-inner"><span className="guarantee-mark">30<span>DAYS</span></span><div><p className="eyebrow">PROPOSED GUARANTEE · MOCKUP OFFER</p><h3>Open it. Fill in a section. See what changes.</h3><p>If it doesn’t help you create a clearer family hand-off, ask for a full refund within 30 days.</p></div></div></section>
<section className="final-cta section wrap"><h2>They’ll have enough on their mind.<br/><em>Leave them one less thing to figure out.</em></h2><p>Get the binder. Put the answers in place. Let them know where to start.</p><a className="button" href="#offer">Get My Family Binder — $27 <span>→</span></a><p className="micro">PDF + Notion · Printable safe-copy · Lifetime updates</p></section><footer className="wrap"><a className="brand" href="#">THE FAMILY SAFEKEEP<span>IN CASE OF EVERYTHING.</span></a><small>Private concept · No live purchases</small></footer><Dialog open={open} onOpenChange={setOpen}><DialogContent className="checkout-dialog"><DialogHeader><DialogTitle>Your family’s starting point.</DialogTitle><DialogDescription>This is a checkout preview. No payment will be taken.</DialogDescription></DialogHeader><div className="checkout-line"><span>If I’m Not Here binder</span><strong>$27</strong></div>{bump&&<div className="checkout-line"><span>First 48 Hours checklist</span><strong>$17</strong></div>}<div className="checkout-line"><strong>Total</strong><strong>${bump?44:27}</strong></div><button className="button" onClick={()=>setOpen(false)}>Back to the binder →</button></DialogContent></Dialog></main>}
