'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import copy from './safekeep-copy.json';
import './safekeep.css';

function Paragraphs({items}:{items:string[]}){return <>{items.map((text,i)=><p key={i}>{text}</p>)}</>}
function Check(){return <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="m8 12 3 3 5-6"/></svg>}
export default function Home(){
 const [bump,setBump]=useState(false);
 const [open,setOpen]=useState(false);
 return <main className="sf">
  <div className="sf-alert">{copy.alert}</div>
  <header className="sf-hero">
   <div className="sf-container sf-hero-grid">
    <div><span className="sf-pill">{copy.eyebrow}</span><h1>{copy.headline.split(', ')[0]},<br/><em>{copy.headline.split(', ').slice(1).join(', ')}</em></h1><p className="sf-lead">{copy.lead}</p><div className="sf-hero-action"><a className="sf-button" href="#checkout-section">{copy.cta}</a><p className="sf-trust">{copy.trust}</p></div></div>
    <figure className="sf-hero-photo"><img src="https://storage.googleapis.com/msgsndr/fveUHPreYRqiA1APSbJt/media/694ed94d73a5e00f27327df7.jpg" alt="A woman organising family paperwork at her kitchen table"/><figcaption>{copy.caption}</figcaption></figure>
   </div>
  </header>
  <section className="sf-section sf-story"><div className="sf-narrow"><div className="sf-heading">{copy.story.eyebrow && <span className="sf-script">{copy.story.eyebrow}</span>}<h2>{copy.story.title}</h2></div><div className="sf-prose">{copy.story.paragraphs.map((text,i)=><p key={i} className={i===5?"sf-story-quote":undefined}>{i===2||i===5?<em>{text}</em>:i===3?<>{text.slice(0,text.indexOf("I’m"))}<strong>{text.slice(text.indexOf("I’m"))}</strong></>:text}</p>)}</div></div></section>
  <section className="sf-section sf-white"><div className="sf-medium"><h2 className="sf-heading">{copy.alternatives.title}</h2><div className="sf-alternatives">{copy.alternatives.items.map(item=><article key={item.title}><h3><span aria-hidden="true">×</span>{item.title}</h3><Paragraphs items={item.paragraphs}/></article>)}</div>{copy.alternatives.close && <p className="sf-dark-statement">{copy.alternatives.close}</p>}</div></section>
  <section className="sf-section sf-solution"><div className="sf-solution-inner">{copy.solution.eyebrow && <span className="sf-eyebrow">{copy.solution.eyebrow}</span>}<h2>{copy.solution.title}</h2>{copy.solution.paragraphs.map((text,i)=><p key={i}>{i===copy.solution.paragraphs.length-1?<strong>{text}</strong>:text}</p>)}</div></section>
  <section className="sf-section sf-white"><div className="sf-container"><div className="sf-product-grid"><div><h2 className="sf-product-name">{copy.product.brand}</h2><p className="sf-script sf-subtitle">{copy.product.subtitle}</p><p className="sf-product-intro">{copy.product.intro}</p><div className="sf-contents">{copy.product.items.map(item=><div className="sf-content-row" key={item.title}><Check/><div><h3>{item.title}</h3><Paragraphs items={item.paragraphs}/></div></div>)}</div></div><img className="sf-product-image" src="/family-safekeep-product.png" alt="The Family Safekeep If I’m Not Here Binder on a laptop, tablet and phone" width="1536" height="1024" loading="lazy"/></div><figure className="sf-testimonial"><div className="sf-stars" aria-label="5 out of 5 stars">★★★★★</div><blockquote>{copy.testimonial.quote}</blockquote><figcaption>{copy.testimonial.name}</figcaption></figure></div></section>
  <section className="sf-section"><div className="sf-medium"><h2 className="sf-heading">{copy.objections.title}</h2><div className="sf-objections">{copy.objections.items.map(item=><article key={item.title}><h3>{item.title}</h3><Paragraphs items={item.paragraphs}/></article>)}</div></div></section>
  <section className="sf-section sf-mechanism"><div className="sf-container"><h2 className="sf-heading">{copy.mechanism.title}</h2><div className="sf-mechanism-grid">{copy.mechanism.items.map((item,i)=><article key={item.title}><span className="sf-mechanism-icon" aria-hidden="true">{['☷','⊞','◷'][i]}</span><h3>{item.title}</h3><Paragraphs items={item.paragraphs}/></article>)}</div></div></section>
  <section className="sf-section sf-guarantee"><div className="sf-narrow"><div className="sf-seal" aria-hidden="true">✓</div><h2>{copy.guarantee.title}</h2><Paragraphs items={copy.guarantee.paragraphs}/></div></section>
  <section className="sf-section sf-white sf-checkout" id="checkout-section"><div className="sf-narrow"><div className="sf-offer-heading"><h2>{copy.offer.brand}</h2><p className="sf-offer-subtitle">{copy.offer.subtitle}</p><div className="sf-price"><del>{copy.offer.oldPrice}</del><strong>{copy.offer.price}</strong></div><span className="sf-launch">{copy.offer.label}</span><ul className="sf-included">{copy.offer.features.map(x=><li key={x}><span aria-hidden="true">✓</span>{x}</li>)}</ul><div className="sf-payment"><Paragraphs items={copy.offer.payment}/></div></div><label className="sf-bump"><input type="checkbox" checked={bump} onChange={e=>setBump(e.target.checked)}/><div><h3>{copy.bump.title}</h3>{copy.bump.paragraphs.map((text,i)=><p key={i}>{i===copy.bump.paragraphs.length-1?<strong>{text}</strong>:text}</p>)}<div className="sf-bump-price">{copy.bump.oldPrice && <del>{copy.bump.oldPrice}</del>}<strong>{copy.bump.price}</strong></div></div></label><button className="sf-button sf-buy" onClick={()=>setOpen(true)}>{copy.cta}</button><p className="sf-total" aria-live="polite">Your total: ${bump?44:27}</p><p className="sf-checkout-trust">{copy.trust}</p></div></section>
  <section className="sf-section sf-faq"><div className="sf-narrow"><h2 className="sf-heading">{copy.faq.title}</h2><div className="sf-faq-list">{copy.faq.items.map(item=><article key={item.title}><h3>{item.title}</h3><Paragraphs items={item.paragraphs}/></article>)}</div><figure className="sf-final-testimonial"><blockquote>{copy.finalTestimonial.quote}</blockquote><figcaption>{copy.finalTestimonial.name}</figcaption></figure></div></section>
  <section className="sf-section sf-white sf-final"><div className="sf-solution-inner"><h2>{copy.final.title}</h2><Paragraphs items={copy.final.paragraphs}/><a className="sf-button sf-button-navy" href="#checkout-section">{copy.final.cta}</a><p className="sf-checkout-trust">{copy.final.trust}</p><img src="https://storage.googleapis.com/msgsndr/fveUHPreYRqiA1APSbJt/media/694ed952b62dd34687da4510.jpg" alt="Hands holding a family photograph" width="512" loading="lazy"/></div></section>
  <footer className="sf-footer"><strong>{copy.product.brand}</strong><small>Private concept · No live purchases</small></footer>
  <Dialog open={open} onOpenChange={setOpen}><DialogContent className="checkout-dialog"><DialogHeader><DialogTitle>{copy.product.brand}</DialogTitle><DialogDescription>This is a checkout preview. No payment will be taken.</DialogDescription></DialogHeader><div className="checkout-line"><span>{copy.product.subtitle}</span><strong>$27</strong></div>{bump&&<div className="checkout-line"><span>First 48 Hours Guide</span><strong>$17</strong></div>}<div className="checkout-line"><strong>Total</strong><strong>${bump?44:27}</strong></div><button className="sf-button" onClick={()=>setOpen(false)}>Back to the binder</button></DialogContent></Dialog>
 </main>;
}
